### PR TITLE
fix: add default value for array/map properties

### LINKED ISSUE #2099: v0.279.0 to v0.285.0, getResources() now returns null.
After changing the version from v0.279.0 to v0.280.0, getResources() now returns null.

use Google_Service_ShoppingContent.

#### Environment details

  - PHP version: 8.1.12
  - Package name and version: google/apiclient-services v0.280.0

#### Code example

```php
# example

    $params = ['maxResults' => 100];
    $service = new \Google_Service_ShoppingContent($client);
    $response = $service->productstatuses->listProductstatuses($this->merchant_center_id, $params);

    foreach ($response->getResources() as $resource) {
        //  $response->getResources() is null
        //  error message : foreach() argument must be of type array|object, null given
    }
```

v0.279.0

v0 279 0

v0.280.0

v0 280 0

v0.280.0 error

v0 280 0_2

Thanks!

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
For array/map properties it changes the generated public property from `public foo;` to `public foo = [];` (hopefully, I haven't tested it)

fixes #2099

### CODE REVIEW

**Review by bshaffer — APPROVED** [review]

**Comment by parallels999** [comment]
Hi, could be https://github.com/masbug/flysystem-google-drive-ext/issues/104 related?

**Comment by maxnz** [comment]
We just started having the same issue as @mfn with the Google Drive API where the `DriveFile`'s `exportLinks` property is rejected because JSON converts it to an empty list instead of an empty map.

**Comment by parallels999** [comment]
Google Drive API, the DriveFile's exportLinks property is rejected
```json
"error": {
    "code": 400,
    "message": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.",
    "errors": [
      {
        "message": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "payload",
            "description": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'."
          }
        ]
      }
    ]
  }
```

**Comment by jacekkarczmarczyk** [comment]
Alternative (and only partial) solution to the original issue would be adding phpdocs comments telling that the property can be null. As I mentioned in the issue now (I mean before merging this PR) it's telling that the value is an array which is not true and is misleading to static code analysers

**Comment by erikn69** [comment]
@bshaffer ping

File: generator/src/googleapis/codegen/languages/php/default/templates/___api_className___/___models_className___.php.tmpl [hunk 1]
```diff
@@ -32,7 +32,7 @@ class {{ model.className }} extends {% if model.superClass %}{{ model.superClass
    */
  {% endif %}
  {% endif %}
-  public ${{ property.memberName }};
+  public ${{ property.memberName }}{% if property.dataType == "array" or property.dataType == "map" %} = []{% endif %};
```
Comment (PaolaRuby) [inline generator/src/googleapis/codegen/languages/php/default/templates/___api_className___/___models_className___.php.tmpl:35]: What about removing map?
```
-public ${{ property.memberName }}{% if property.dataType == "array" or property.dataType == "map" %} = []{% endif %};
+public ${{ property.memberName }}{% if property.dataType == "array" %} = []{% endif %};
```

**Comment by bshaffer** [comment]
It seems like i should just roll this and the other changes back, and just implement dynamic properties on these classes

**Comment by angeljqv** [comment]
> It seems like i should just roll this and the other changes back

@bshaffer @jacekkarczmarczyk 
So, does #2351 fix `empty list instead of an empty map`?

**Comment by maxnz** [comment]
It looks like these changes were re-released automatically as part of v0.290.0?
https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.290.0
